app.core.biu:
  common:
    press_to_exit: "按任意键退出..."
    success_to_login: "登录成功"
  config:
    hint_port_is_in_use: "现端口已被占用，请修改 config.yml 中的 sys.host 配置项"
    hint_proxy_in_use: "已启用代理 %s"
    fail_to_load_config: "读取配置文件失败，程序无法正常运行"
  outdated:
    hint_latest: "最新"
    hint_exist_new: "有新版本可用"
    fail_to_check: "检测更新失败"
    fail_to_check_duo_to_network: "检测更新失败，可能是目标服务器过长时间未响应"
    tell_to_download: "访问 https://github.com/txperl/PixivBiu/releases 即可下载"
    press_to_use_old: "按任意键以继续使用旧版本..."
  network:
    hint_in_check: "检测网络状态..."
    fail_pixiv_and_use_bypass: "无法访问 Pixiv，启用 bypassSNI 线路 (可能无法正常使用)"
  login:
    hint_token_only: "由于 Pixiv 禁止了账号密码登陆方式，目前只能使用 Token 进行登录"
    hint_before_start: "即将开始进行网络检测，此过程可以减少因网络问题导致的无法正常使用 PixivBiu 的概率"
    fail_to_get_token_due_to_network: "您的网络无法正常进行 Pixiv Token 登陆，请调整后重试"
    fail_to_get_token_anyway: "获取 Token 时出错，请重试"
    fail_by_cloudflare_captcha: "登录时遇到 Cloudflare 保护，可能是网络环境问题导致。您可以尝试重新获取 Token，或稍等片刻后再次登录"
    is_need_to_get_token: "程序将引导你获取 Token，是否继续? (y / n): "
  ready:
    hint_run: "运行:"
    hint_how_to_use: "将地址输入现代浏览器即可使用"
    hint_version: "版本:"
    hint_function_types: "功能类型:"
    hint_image_service: "图片服务:"
    hint_download_path: "下载保存路径:"
    hint_program_path: "程序目录"
    done_init: "初始化完成"
  others:
    hint_in_update_token: "尝试 Token 更新"

app.common.loginHelper:
  network:
    press_need_to_type_proxy: "请输入代理地址（可留空）: "
    hint_detect_proxy: "检测到为 %s 的代理地址，是否需要更改? (y / n): "
    is_need_to_type_proxy: "未能检测到代理地址，是否需要手动设置? (y / n): "
  login:
    hint_intro_step_head: "[Login] 请按以下步骤进行操作:"
    hint_intro_step_1: "1. 访问: %s?%s"
    hint_intro_step_2: "2. 打开浏览器的「Dev Console / 开发者工具」，切换至「Network / 网络」标签页"
    hint_intro_step_3: "3. 开启「Preserve log / 持续记录」"
    hint_intro_step_4: "4. 在「Filter / 筛选」文本框中输入「callback?」"
    hint_intro_step_5: "5. 登录您的 Pixiv 账号"
    hint_intro_step_6: "6. 成功登录后，会出现一个类似「https://app-api.pixiv.net/...&code=...」的字段"
    hint_intro_step_7: "7. 将「code」后面的参数输入本程序"
    fail_code_918: "Code 错误。请注意程序每次启动时要求获取的 Code 都不同，不可复用之前获取到的，且 Code 不带有引号。"
    fail_code_1508: "Code 已过期。请在进行 Code 获取操作时快一些。"
